version: '3.6'
services:
  postgres:
    image: postgres:12
    restart: always
    ports:
    - "5432:5432"
    expose:
    - "5432"
    volumes:
    - db_data:/var/lib/postgresql/data
    - ./init_db.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_PASSWORD: t-h0]hAh~b8G=O=f3Eo
      POSTGRES_HOST_AUTH_METHOD: trust
  graphql-engine:
    image: hasura/graphql-engine:v2.0.0-alpha.7
    ports:
    - "8000:8080"
    expose:
      - "8000"
    depends_on:
    - "postgres"
    restart: always
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:t-h0]hAh~b8G=O=f3Eo@postgres:5432/postgres
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true"
      HASURA_GRAPHQL_DEV_MODE: "true"
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
      HASURA_GRAPHQL_ADMIN_SECRET: D!G!TALREBELL1on
      HASURA_GRAPHQL_UNAUTHORIZED_ROLE: "public"
volumes:
  db_data:
